import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";
import { GoogleAnalytics } from '@next/third-parties/google'
import AnalyticsDebug from "./components/AnalyticsDebug";


// Custom font import (local fonts)
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="sv">
      <head>
        <link rel="icon" href="/img/JGruppen-logo.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Triodion&display=swap"
          rel="stylesheet"
        />
        {/* Google Analytics via Next.js third-parties integration */}
        <GoogleAnalytics gaId={process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* We don't need the AnalyticsWrapper if we're using the Next.js GA component */}
        <Header />
        <div className="triodion-regular">
          <div className="font-wrapper">
            {children}
          </div>
        </div>
        <Footer />
        
        {/* Debug component for development only */}
        <AnalyticsDebug />
      </body>
    </html>
  );
}
